// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package in.srini91.learn.protos;

public interface AddressBookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddressBook)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Employee employee = 1;</code>
   */
  java.util.List<in.srini91.learn.protos.Employee> 
      getEmployeeList();
  /**
   * <code>repeated .Employee employee = 1;</code>
   */
  in.srini91.learn.protos.Employee getEmployee(int index);
  /**
   * <code>repeated .Employee employee = 1;</code>
   */
  int getEmployeeCount();
  /**
   * <code>repeated .Employee employee = 1;</code>
   */
  java.util.List<? extends in.srini91.learn.protos.EmployeeOrBuilder> 
      getEmployeeOrBuilderList();
  /**
   * <code>repeated .Employee employee = 1;</code>
   */
  in.srini91.learn.protos.EmployeeOrBuilder getEmployeeOrBuilder(
      int index);
}
