// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package in.srini91.learn.protos;

public interface EmployeeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Employee)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>optional string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int32 id = 2;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>optional int32 id = 2;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>optional string email = 3;</code>
   * @return Whether the email field is set.
   */
  boolean hasEmail();
  /**
   * <code>optional string email = 3;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>optional string email = 3;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>repeated .Employee.PhoneNumber phones = 4;</code>
   */
  java.util.List<in.srini91.learn.protos.Employee.PhoneNumber> 
      getPhonesList();
  /**
   * <code>repeated .Employee.PhoneNumber phones = 4;</code>
   */
  in.srini91.learn.protos.Employee.PhoneNumber getPhones(int index);
  /**
   * <code>repeated .Employee.PhoneNumber phones = 4;</code>
   */
  int getPhonesCount();
  /**
   * <code>repeated .Employee.PhoneNumber phones = 4;</code>
   */
  java.util.List<? extends in.srini91.learn.protos.Employee.PhoneNumberOrBuilder> 
      getPhonesOrBuilderList();
  /**
   * <code>repeated .Employee.PhoneNumber phones = 4;</code>
   */
  in.srini91.learn.protos.Employee.PhoneNumberOrBuilder getPhonesOrBuilder(
      int index);
}
