// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: credential.proto

package in.srini91.learn.protos.test;

public interface CredentialsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Credentials)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.EmailCredential emailMode = 1;</code>
   * @return Whether the emailMode field is set.
   */
  boolean hasEmailMode();
  /**
   * <code>.EmailCredential emailMode = 1;</code>
   * @return The emailMode.
   */
  in.srini91.learn.protos.test.EmailCredential getEmailMode();
  /**
   * <code>.EmailCredential emailMode = 1;</code>
   */
  in.srini91.learn.protos.test.EmailCredentialOrBuilder getEmailModeOrBuilder();

  /**
   * <code>.PhoneCredential phoneMode = 2;</code>
   * @return Whether the phoneMode field is set.
   */
  boolean hasPhoneMode();
  /**
   * <code>.PhoneCredential phoneMode = 2;</code>
   * @return The phoneMode.
   */
  in.srini91.learn.protos.test.PhoneCredential getPhoneMode();
  /**
   * <code>.PhoneCredential phoneMode = 2;</code>
   */
  in.srini91.learn.protos.test.PhoneCredentialOrBuilder getPhoneModeOrBuilder();

  public in.srini91.learn.protos.test.Credentials.ModeCase getModeCase();
}
