// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package in.srini91.learn.protos.test;

public interface DealerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Dealer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, .Car&gt; model = 1;</code>
   */
  int getModelCount();
  /**
   * <code>map&lt;int32, .Car&gt; model = 1;</code>
   */
  boolean containsModel(
      int key);
  /**
   * Use {@link #getModelMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, in.srini91.learn.protos.test.Car>
  getModel();
  /**
   * <code>map&lt;int32, .Car&gt; model = 1;</code>
   */
  java.util.Map<java.lang.Integer, in.srini91.learn.protos.test.Car>
  getModelMap();
  /**
   * <code>map&lt;int32, .Car&gt; model = 1;</code>
   */

  /* nullable */
in.srini91.learn.protos.test.Car getModelOrDefault(
      int key,
      /* nullable */
in.srini91.learn.protos.test.Car defaultValue);
  /**
   * <code>map&lt;int32, .Car&gt; model = 1;</code>
   */

  in.srini91.learn.protos.test.Car getModelOrThrow(
      int key);
}
