// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: dealer.proto

package in.srini91.learn.protos.test;

public interface DealerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Dealer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>map&lt;int32, .common.Car&gt; model = 1;</code>
   */
  int getModelCount();
  /**
   * <code>map&lt;int32, .common.Car&gt; model = 1;</code>
   */
  boolean containsModel(
      int key);
  /**
   * Use {@link #getModelMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.Integer, in.srini91.learn.protos.test.common.Car>
  getModel();
  /**
   * <code>map&lt;int32, .common.Car&gt; model = 1;</code>
   */
  java.util.Map<java.lang.Integer, in.srini91.learn.protos.test.common.Car>
  getModelMap();
  /**
   * <code>map&lt;int32, .common.Car&gt; model = 1;</code>
   */

  /* nullable */
in.srini91.learn.protos.test.common.Car getModelOrDefault(
      int key,
      /* nullable */
in.srini91.learn.protos.test.common.Car defaultValue);
  /**
   * <code>map&lt;int32, .common.Car&gt; model = 1;</code>
   */

  in.srini91.learn.protos.test.common.Car getModelOrThrow(
      int key);

  /**
   * <code>.common.Address address = 2;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.common.Address address = 2;</code>
   * @return The address.
   */
  in.srini91.learn.protos.test.common.Address getAddress();
  /**
   * <code>.common.Address address = 2;</code>
   */
  in.srini91.learn.protos.test.common.AddressOrBuilder getAddressOrBuilder();
}
