// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: credential.proto

package in.srini91.learn.protos.test;

public interface EmailCredentialOrBuilder extends
    // @@protoc_insertion_point(interface_extends:EmailCredential)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string email = 1;</code>
   * @return The email.
   */
  java.lang.String getEmail();
  /**
   * <code>string email = 1;</code>
   * @return The bytes for email.
   */
  com.google.protobuf.ByteString
      getEmailBytes();

  /**
   * <code>string pwd = 2;</code>
   * @return The pwd.
   */
  java.lang.String getPwd();
  /**
   * <code>string pwd = 2;</code>
   * @return The bytes for pwd.
   */
  com.google.protobuf.ByteString
      getPwdBytes();
}
