// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

package in.srini91.learn.protos.test;

public interface PersonOrBuilder extends
    // @@protoc_insertion_point(interface_extends:Person)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 age = 2;</code>
   * @return The age.
   */
  int getAge();

  /**
   * <code>.common.Address address = 3;</code>
   * @return Whether the address field is set.
   */
  boolean hasAddress();
  /**
   * <code>.common.Address address = 3;</code>
   * @return The address.
   */
  in.srini91.learn.protos.test.common.Address getAddress();
  /**
   * <code>.common.Address address = 3;</code>
   */
  in.srini91.learn.protos.test.common.AddressOrBuilder getAddressOrBuilder();

  /**
   * <code>repeated .common.Car car = 4;</code>
   */
  java.util.List<in.srini91.learn.protos.test.common.Car> 
      getCarList();
  /**
   * <code>repeated .common.Car car = 4;</code>
   */
  in.srini91.learn.protos.test.common.Car getCar(int index);
  /**
   * <code>repeated .common.Car car = 4;</code>
   */
  int getCarCount();
  /**
   * <code>repeated .common.Car car = 4;</code>
   */
  java.util.List<? extends in.srini91.learn.protos.test.common.CarOrBuilder> 
      getCarOrBuilderList();
  /**
   * <code>repeated .common.Car car = 4;</code>
   */
  in.srini91.learn.protos.test.common.CarOrBuilder getCarOrBuilder(
      int index);
}
