// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: credential.proto

package in.srini91.learn.protos.test;

public interface PhoneCredentialOrBuilder extends
    // @@protoc_insertion_point(interface_extends:PhoneCredential)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 phoneNo = 1;</code>
   * @return The phoneNo.
   */
  int getPhoneNo();

  /**
   * <code>int32 otp = 2;</code>
   * @return The otp.
   */
  int getOtp();
}
