// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: credential.proto

package in.srini91.learn.protos.test;

/**
 * Protobuf type {@code PhoneCredential}
 */
public final class PhoneCredential extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:PhoneCredential)
    PhoneCredentialOrBuilder {
private static final long serialVersionUID = 0L;
  // Use PhoneCredential.newBuilder() to construct.
  private PhoneCredential(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private PhoneCredential() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new PhoneCredential();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private PhoneCredential(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            phoneNo_ = input.readInt32();
            break;
          }
          case 16: {

            otp_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (com.google.protobuf.UninitializedMessageException e) {
      throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return in.srini91.learn.protos.test.Credential.internal_static_PhoneCredential_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return in.srini91.learn.protos.test.Credential.internal_static_PhoneCredential_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            in.srini91.learn.protos.test.PhoneCredential.class, in.srini91.learn.protos.test.PhoneCredential.Builder.class);
  }

  public static final int PHONENO_FIELD_NUMBER = 1;
  private int phoneNo_;
  /**
   * <code>int32 phoneNo = 1;</code>
   * @return The phoneNo.
   */
  @java.lang.Override
  public int getPhoneNo() {
    return phoneNo_;
  }

  public static final int OTP_FIELD_NUMBER = 2;
  private int otp_;
  /**
   * <code>int32 otp = 2;</code>
   * @return The otp.
   */
  @java.lang.Override
  public int getOtp() {
    return otp_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (phoneNo_ != 0) {
      output.writeInt32(1, phoneNo_);
    }
    if (otp_ != 0) {
      output.writeInt32(2, otp_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (phoneNo_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, phoneNo_);
    }
    if (otp_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, otp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof in.srini91.learn.protos.test.PhoneCredential)) {
      return super.equals(obj);
    }
    in.srini91.learn.protos.test.PhoneCredential other = (in.srini91.learn.protos.test.PhoneCredential) obj;

    if (getPhoneNo()
        != other.getPhoneNo()) return false;
    if (getOtp()
        != other.getOtp()) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + PHONENO_FIELD_NUMBER;
    hash = (53 * hash) + getPhoneNo();
    hash = (37 * hash) + OTP_FIELD_NUMBER;
    hash = (53 * hash) + getOtp();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static in.srini91.learn.protos.test.PhoneCredential parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static in.srini91.learn.protos.test.PhoneCredential parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(in.srini91.learn.protos.test.PhoneCredential prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code PhoneCredential}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:PhoneCredential)
      in.srini91.learn.protos.test.PhoneCredentialOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return in.srini91.learn.protos.test.Credential.internal_static_PhoneCredential_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return in.srini91.learn.protos.test.Credential.internal_static_PhoneCredential_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              in.srini91.learn.protos.test.PhoneCredential.class, in.srini91.learn.protos.test.PhoneCredential.Builder.class);
    }

    // Construct using in.srini91.learn.protos.test.PhoneCredential.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      phoneNo_ = 0;

      otp_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return in.srini91.learn.protos.test.Credential.internal_static_PhoneCredential_descriptor;
    }

    @java.lang.Override
    public in.srini91.learn.protos.test.PhoneCredential getDefaultInstanceForType() {
      return in.srini91.learn.protos.test.PhoneCredential.getDefaultInstance();
    }

    @java.lang.Override
    public in.srini91.learn.protos.test.PhoneCredential build() {
      in.srini91.learn.protos.test.PhoneCredential result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public in.srini91.learn.protos.test.PhoneCredential buildPartial() {
      in.srini91.learn.protos.test.PhoneCredential result = new in.srini91.learn.protos.test.PhoneCredential(this);
      result.phoneNo_ = phoneNo_;
      result.otp_ = otp_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof in.srini91.learn.protos.test.PhoneCredential) {
        return mergeFrom((in.srini91.learn.protos.test.PhoneCredential)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(in.srini91.learn.protos.test.PhoneCredential other) {
      if (other == in.srini91.learn.protos.test.PhoneCredential.getDefaultInstance()) return this;
      if (other.getPhoneNo() != 0) {
        setPhoneNo(other.getPhoneNo());
      }
      if (other.getOtp() != 0) {
        setOtp(other.getOtp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      in.srini91.learn.protos.test.PhoneCredential parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (in.srini91.learn.protos.test.PhoneCredential) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int phoneNo_ ;
    /**
     * <code>int32 phoneNo = 1;</code>
     * @return The phoneNo.
     */
    @java.lang.Override
    public int getPhoneNo() {
      return phoneNo_;
    }
    /**
     * <code>int32 phoneNo = 1;</code>
     * @param value The phoneNo to set.
     * @return This builder for chaining.
     */
    public Builder setPhoneNo(int value) {
      
      phoneNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 phoneNo = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearPhoneNo() {
      
      phoneNo_ = 0;
      onChanged();
      return this;
    }

    private int otp_ ;
    /**
     * <code>int32 otp = 2;</code>
     * @return The otp.
     */
    @java.lang.Override
    public int getOtp() {
      return otp_;
    }
    /**
     * <code>int32 otp = 2;</code>
     * @param value The otp to set.
     * @return This builder for chaining.
     */
    public Builder setOtp(int value) {
      
      otp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 otp = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearOtp() {
      
      otp_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:PhoneCredential)
  }

  // @@protoc_insertion_point(class_scope:PhoneCredential)
  private static final in.srini91.learn.protos.test.PhoneCredential DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new in.srini91.learn.protos.test.PhoneCredential();
  }

  public static in.srini91.learn.protos.test.PhoneCredential getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<PhoneCredential>
      PARSER = new com.google.protobuf.AbstractParser<PhoneCredential>() {
    @java.lang.Override
    public PhoneCredential parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new PhoneCredential(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<PhoneCredential> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<PhoneCredential> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public in.srini91.learn.protos.test.PhoneCredential getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

