// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package in.srini91.learn.protos.test;

public final class Test {
  private Test() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Address_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Address_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Car_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Car_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Person_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Person_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dealer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dealer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Dealer_ModelEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Dealer_ModelEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ntest.proto\"8\n\007Address\022\017\n\007postbox\030\001 \001(\005" +
      "\022\016\n\006street\030\002 \001(\t\022\014\n\004city\030\003 \001(\t\"0\n\003Car\022\014\n" +
      "\004make\030\001 \001(\t\022\r\n\005model\030\002 \001(\t\022\014\n\004year\030\003 \001(\005" +
      "\"Q\n\006Person\022\014\n\004name\030\001 \001(\t\022\013\n\003age\030\002 \001(\005\022\031\n" +
      "\007address\030\003 \001(\0132\010.Address\022\021\n\003car\030\004 \003(\0132\004." +
      "Car\"_\n\006Dealer\022!\n\005model\030\001 \003(\0132\022.Dealer.Mo" +
      "delEntry\0322\n\nModelEntry\022\013\n\003key\030\001 \001(\005\022\023\n\005v" +
      "alue\030\002 \001(\0132\004.Car:\0028\001B \n\034in.srini91.learn" +
      ".protos.testP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Address_descriptor,
        new java.lang.String[] { "Postbox", "Street", "City", });
    internal_static_Car_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Car_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Car_descriptor,
        new java.lang.String[] { "Make", "Model", "Year", });
    internal_static_Person_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Person_descriptor,
        new java.lang.String[] { "Name", "Age", "Address", "Car", });
    internal_static_Dealer_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_Dealer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dealer_descriptor,
        new java.lang.String[] { "Model", });
    internal_static_Dealer_ModelEntry_descriptor =
      internal_static_Dealer_descriptor.getNestedTypes().get(0);
    internal_static_Dealer_ModelEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Dealer_ModelEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
